// <auto-generated />
using System;
using LibraryManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagementSystem.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260329163419_FixPasswords")]
    partial class FixPasswords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("LibraryManagementSystem.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$zP8zaB7NuZ.a38xCp5..yu0Ik5irGzIGqqPepVQ2YV6DeTv4NfZLy",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "$2a$11$KnITbSDoQR8i2FeCFKjEruu.7fKFpDdgNLyjmaQhSqUoLtASNoZnK",
                            Role = "User",
                            Username = "libraryuser"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CopiesAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Chimamanda Ngozi Adichie",
                            CopiesAvailable = 5,
                            ISBN = "9781616953638",
                            Title = "Purple Hibiscus"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Chimamanda Ngozi Adichie",
                            CopiesAvailable = 4,
                            ISBN = "9781400095209",
                            Title = "Half of a Yellow Sun"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Chimamanda Ngozi Adichie",
                            CopiesAvailable = 6,
                            ISBN = "9780307455925",
                            Title = "Americanah"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jordan Peterson",
                            CopiesAvailable = 3,
                            ISBN = "9780345816023",
                            Title = "12 Rules for Life"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Jordan Peterson",
                            CopiesAvailable = 2,
                            ISBN = "9780593084649",
                            Title = "Beyond Order"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Chinua Achebe",
                            CopiesAvailable = 7,
                            ISBN = "9780385474542",
                            Title = "Things Fall Apart"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Ben Okri",
                            CopiesAvailable = 3,
                            ISBN = "9780385425148",
                            Title = "The Famished Road"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.BorrowRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BorrowedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BorrowRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            BorrowedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowedBy = "alice",
                            ReturnedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            BorrowedAt = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowedBy = "bob",
                            ReturnedAt = new DateTime(2024, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BookId = 1,
                            BorrowedAt = new DateTime(2024, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowedBy = "carol",
                            ReturnedAt = new DateTime(2024, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            BookId = 1,
                            BorrowedAt = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowedBy = "dave",
                            ReturnedAt = new DateTime(2024, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            BookId = 1,
                            BorrowedAt = new DateTime(2024, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowedBy = "eve"
                        },
                        new
                        {
                            Id = 6,
                            BookId = 3,
                            BorrowedAt = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowedBy = "frank",
                            ReturnedAt = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            BookId = 3,
                            BorrowedAt = new DateTime(2024, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowedBy = "grace",
                            ReturnedAt = new DateTime(2024, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            BookId = 3,
                            BorrowedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowedBy = "hank",
                            ReturnedAt = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            BookId = 3,
                            BorrowedAt = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowedBy = "ivan"
                        },
                        new
                        {
                            Id = 10,
                            BookId = 5,
                            BorrowedAt = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowedBy = "judy",
                            ReturnedAt = new DateTime(2024, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            BookId = 5,
                            BorrowedAt = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowedBy = "kyle",
                            ReturnedAt = new DateTime(2024, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            BookId = 5,
                            BorrowedAt = new DateTime(2024, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowedBy = "lisa"
                        },
                        new
                        {
                            Id = 13,
                            BookId = 2,
                            BorrowedAt = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowedBy = "mike",
                            ReturnedAt = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            BookId = 2,
                            BorrowedAt = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowedBy = "nina"
                        },
                        new
                        {
                            Id = 15,
                            BookId = 4,
                            BorrowedAt = new DateTime(2024, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BorrowedBy = "omar",
                            ReturnedAt = new DateTime(2024, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.BorrowRecord", b =>
                {
                    b.HasOne("LibraryManagementSystem.Models.Book", "Book")
                        .WithMany("BorrowRecords")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.Book", b =>
                {
                    b.Navigation("BorrowRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
